const ACTION = {
  INPUT_SET_BALANCE: 'INPUT_SET_BALANCE',
  INPUT_SET_PRICE_USD: 'INPUT_SET_PRICE_USD',
  INPUT_SET_AMOUNT: 'INPUT_SET_AMOUNT',
  INPUT_SET_SYMBOL: 'INPUT_SET_SYMBOL',
  OUTPUT_SET_BALANCE: 'OUTPUT_SET_BALANCE',
  OUTPUT_SET_PRICE_USD: 'OUTPUT_SET_PRICE_USD',
  OUTPUT_SET_AMOUNT: 'OUTPUT_SET_AMOUNT',
  OUTPUT_SET_SYMBOL: 'OUTPUT_SET_SYMBOL',
  REVERT: 'REVERT',
  SET_SWAP_TYPE: 'SET_SWAP_TYPE',
  LOCK_ON: 'LOCK_ON',
  LOCK_OFF: 'LOCK_OFF',
  REVERT_LOADING_ON: 'REVERT_LOADING_ON',
  REVERT_LOADING_OFF: 'REVERT_LOADING_OFF',
  CALCULATE_LOADING_OFF: 'CALCULATE_LOADING_OFF',
  CALCULATE_LOADING_ON: 'CALCULATE_LOADING_ON',
};

export default ACTION;