const SWAP_TYPE = {
  BUY: {
    EXACT_ETH_FOR_TOKENS: "EXACT_ETH_FOR_TOKENS",
  },
  SELL: {
    EXACT_TOKENS_FOR_ETH: "EXACT_TOKENS_FOR_ETH",
    TOKENS_FOR_EXACT_ETH: "TOKENS_FOR_EXACT_ETH",
  },
};

export default SWAP_TYPE;

